---
- hosts: test
  gather_facts: false
  connection: local
  tasks:
    - name: "TASK 1: run show version on the routers"
      ios_command:
        commands: show version | incl Version
      register: output

    - name: print output
      debug:
        var: output.stdout

    - name: "TASK 2: get interfaces"
      ios_command:
        commands: show ip interface brief | exclude unassigned
      register: interfaces

    - debug: var=interfaces.stdout_lines[0][1].split()[1]
    - debug: var=interfaces.stdout_lines[0][2].split()[1]
