---
- hosts: prouters
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Merge provided configuration with device configuration
      cisco.ios.ios_l3_interfaces:
        config:
        - name: "{{ item.name }}"
          ipv4:
          - address: "{{ item.address }}"
        state: merged
      loop:
        - "{{ interfaces }}"
